[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install --no-cache-dir 'python-telegram-bot[job-queue]==21.3' requests==2.32.3 beautifulsoup4==4.12.3"]

[start]
cmd = "python main.py"
